# Generated by Django 4.2.6 on 2023-10-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotdog_stands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.TextField()),
                ("time_sent", models.DateTimeField(auto_now_add=True)),
                (
                    "hotdog_stand",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hotdog_stands.hotdogstand"),
                ),
            ],
        ),
    ]
